# Generated by Django 4.0.6 on 2022-07-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='memo',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
